LOCAL_PATH := $(call my-dir)

#Files
include $(CLEAR_VARS)
LOCAL_MODULE := FilesD
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := priv-app/FilesD/FilesD.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
include $(BUILD_PREBUILT)
